#!/bin/sh
set -e

echo 'npx tsc...'
npx tsc

echo 'building...'
npm run build-prod

echo 'syncing to s3'
    aws s3 sync dist s3://yallwork \
    --delete \
    --acl private \
    --exclude *.DS_Store

echo 'invalidating cloudfront cache'
aws cloudfront create-invalidation --distribution-id E1ZU2PHJZ0QQEC --paths "/*"

echo '🎉'